### ISSUE TITLE
Bug #1 "Your internet is slow" Showing when shouldn't 

### ISSUE THREAD

**Issue by jdc20181** [jdc20181/SpeedTest#10]
This last release was a double release as I updated the changelog but didnt make the release. 

So I added or tried to add some more JS to tell users thier OS and browser. 

The "Js is turned off or your internet is slwo" message came and didn't work. 

I reverted, and now for about 3 seconds you will see the "error" message. 

Its annoying!

**Comment by jdc20181** [comment]
A Temp Fix will be coming soon!

**Comment by amanuel2** [comment]
Who cares lol?

**Comment by jdc20181** [comment]
Will be fixed in Version 0.5.0

**Comment by jdc20181** [comment]
Just a quick update on this bug - it actually returned a little later, but  I didn't want to re-open the issue. To fix it I did away with it entirely unless you look at console (as that is just how it works-  the results are written in console, and to the html)  instead of "Loading" text you get a Loader, its more design friendly, and somehow increased the accuracy by around 15%, the overall acurracy is near 90%.

**Comment by jdc20181** [comment]
**Fixed/Resolved**
